package com.revature.paymore.model.dto;

import com.revature.paymore.model.Address;

// Assuming you have a simplified AddressDTO, you might want to use it instead of the Address entity
// import com.revature.paymore.model.dto.AddressDTO;

import java.util.Objects;

public class SellerDTO {
    private Long id;
    private String companyName;
    private String email;
    private String username;
    // Consider using AddressDTO instead if you're exposing address details
    private Address address;

    // Constructors, Getters, and Setters

    public SellerDTO() {
    }

    public SellerDTO(Long id, String companyName, String email, String username, Address address) {
        this.id = id;
        this.companyName = companyName;
        this.email = email;
        this.username = username;
        this.address = address;
    }

    // Standard getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    // Equals, hashCode, and toString methods can be generated by your IDE

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SellerDTO)) return false;
        SellerDTO sellerDTO = (SellerDTO) o;
        return Objects.equals(id, sellerDTO.id) &&
                Objects.equals(companyName, sellerDTO.companyName) &&
                Objects.equals(email, sellerDTO.email) &&
                Objects.equals(username, sellerDTO.username) &&
                Objects.equals(address, sellerDTO.address);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, companyName, email, username, address);
    }

    @Override
    public String toString() {
        return "SellerDTO{" +
                "id=" + id +
                ", companyName='" + companyName + '\'' +
                ", email='" + email + '\'' +
                ", username='" + username + '\'' +
                ", address=" + address +
                '}';
    }
}